(()=>{
  'use strict';
  const operational=['Item Name','Record Type','Category','Project','Currency','Payment Amount','Payment Frequency','Monthly Amount','Yearly Amount','Start Date','End Date','Vendor','Notes'];
  const client=['Client ID','Client Name','Project','Pricing Model','Modules','Employee Count','Currency','Monthly Billing Amount','Target Increase Percentage','Start Date','Status'];
  const clean=v=>String(v??'').replace(/^\uFEFF/,'').trim();
  function normalizeHeader(v){return clean(v).toLowerCase().replace(/\s+/g,' ')}
  function normalizeText(v){return clean(v)}
  function normalizeNumber(v){if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;const n=Number(String(v).replace(/[$, ]/g,''));return Number.isFinite(n)?n:null}
  function normalizeDate(v){if(v===null||v===undefined||v==='')return null;if(v instanceof Date&&!isNaN(v))return new Date(v.getFullYear(),v.getMonth(),v.getDate());if(typeof v==='number'){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return isNaN(d)?null:new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())}const s=clean(v), iso=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/), d=iso?new Date(+iso[1],+iso[2]-1,+iso[3]):new Date(s);return isNaN(d)?null:new Date(d.getFullYear(),d.getMonth(),d.getDate())}
  function normalizeCurrency(v){return normalizeText(v).toUpperCase()}
  function normalizeStatus(v){return normalizeText(v)}
  function normalizeRecordType(value){const normalized=String(value??'').trim().toLowerCase();if(normalized==='operational')return 'Operational';if(normalized==='debt')return 'Debt';return null}
  function normalizePricingModel(value){const key=String(value??'').trim().replace(/\s+/g,' ').toLowerCase();if(key==='per employee per module')return 'Per Employee Per Module';if(key==='current billing + percentage')return 'Current Billing + Percentage';return null}
  function csvParse(t){const out=[];let row=[],field='',quoted=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(quoted){if(c==='"'&&n==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(field);field=''}else if(c==='\n'||c==='\r'){if(c==='\r'&&n==='\n')i++;row.push(field);field='';if(row.some(x=>x.trim()))out.push(row);row=[]}else field+=c}if(field||row.length){row.push(field);if(row.some(x=>x.trim()))out.push(row)}return out}
  async function parseCsvFile(file){const text=file.text?await file.text():await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsText(file)});const parsed=csvParse(text);return {headers:(parsed.shift()||[]).map(clean),rows:parsed,metadata:{fileName:file.name,fileType:'csv',sheetName:''}}}
  function matchingSheets(workbook,expected){const required=expected==='operational'?operational:client.filter(x=>x!=='Pricing Model'&&x!=='Target Increase Percentage');return workbook.SheetNames.filter(name=>{const rows=XLSX.utils.sheet_to_json(workbook.Sheets[name],{header:1,raw:true,defval:''});const header=(rows[0]||[]).map(normalizeHeader);return required.every(x=>header.includes(normalizeHeader(x)))})}
  async function parseXlsxFile(file,expected){let workbook;try{workbook=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,bookVBA:false})}catch(e){throw new Error('The XLSX workbook is corrupt, password-protected, or could not be read.')};const matches=matchingSheets(workbook,expected);if(!matches.length)throw new Error('No matching '+(expected==='operational'?'operational-cost':'client-revenue')+' worksheet. Required columns: '+(expected==='operational'?operational:client).join(', ')+'. Inspected worksheets: '+workbook.SheetNames.join(', '));if(matches.length>1){const choice=window.prompt('Select worksheet: '+matches.join(', '),matches[0]);if(!choice||!matches.includes(choice))throw new Error('Multiple matching worksheets found. Choose one of: '+matches.join(', '));}const sheetName=matches.length===1?matches[0]:window.prompt('Select worksheet',matches[0]);const values=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,raw:true,defval:''});if(!values.length)throw new Error('Worksheet '+sheetName+' is empty.');return {headers:(values.shift()||[]).map(clean),rows:values,metadata:{fileName:file.name,fileType:'xlsx',sheetName}}}
  async function parseImportFile(file,expected){const ext=(file.name.split('.').pop()||'').toLowerCase();if(ext==='csv')return parseCsvFile(file);if(ext==='xlsx')return parseXlsxFile(file,expected);throw new Error('Unsupported file type. Choose a CSV or XLSX file. Legacy XLS files are not supported.')}
  window.HRplusImport={parseCsvFile,parseXlsxFile,parseImportFile,normalizeHeader,normalizeText,normalizeNumber,normalizeDate,normalizeCurrency,normalizeStatus,normalizeRecordType,normalizePricingModel,required:{operational,client}};
})();