(() => {
  "use strict";
  let api;
  const $ = (id) => id[0] === "." || id[0] === "#" ? document.querySelector(id) : document.getElementById(id);
  const colors = { operational: "#2671d9", debt: "#d88416", overall: "#243b64", actual: "#159a74", expected: "#7657c9", incomplete: "#c67a12" };
  const money = (value) => Number.isFinite(value) ? "TTD " + new Intl.NumberFormat("en-TT", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value) : "Incomplete";
  const pointX = (index, pad, width, count) => pad.l + width * (index + 0.5) / count;
  const pointY = (value, max, pad, height) => pad.t + height - Math.max(0, value) / max * height;
  function initialize(options) { api = options; $("#previousMonths").onclick = () => scroll(-1); $("#nextMonths").onclick = () => scroll(1); $("#chartScroll").onscroll = updateViewport; $("#trendChart").onpointermove = showTooltip; $("#trendChart").onpointerleave = hideTooltip; render(); }
  function scroll(direction) { $("#chartScroll").scrollBy({ left: direction * Math.max(120, $("#chartScroll").clientWidth / 6) * 6, behavior: "smooth" }); }
  function render() {
    if (!api || !api.state.months.length) return;
    const scrollBox = $("#chartScroll"), width = Math.max(720, scrollBox.clientWidth / 6 * api.state.months.length), height = 420, plot = $(".chart-plot"), canvas = $("#trendChart"), ratio = devicePixelRatio || 1;
    plot.style.width = width + "px"; canvas.width = width * ratio; canvas.height = height * ratio; canvas.style.width = width + "px"; canvas.style.height = height + "px";
    const ctx = canvas.getContext("2d"); ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
    const axis = $("#trendYAxis"); axis.width = 72 * ratio; axis.height = height * ratio; axis.style.width = "72px"; axis.style.height = height + "px"; const axisContext = axis.getContext("2d"); axisContext.setTransform(ratio, 0, 0, ratio, 0, 0);
    const series = api.getSeries(), visible = api.getVisibleSeries(series), max = Math.max(1, ...visible.flat()) * 1.12, pad = { l: 50, r: 18, t: 18, b: 42 }, plotWidth = width - pad.l - pad.r, plotHeight = height - pad.t - pad.b;
    ctx.clearRect(0, 0, width, height); axisContext.clearRect(0, 0, 72, height); drawGrid(ctx, axisContext, max, pad, plotWidth, plotHeight); drawAreas(ctx, series, max, pad, plotWidth, plotHeight); drawLines(ctx, series, max, pad, plotWidth, plotHeight); drawMonthLabels(ctx, series, max, pad, plotWidth, plotHeight); updateControls(series); updateViewport();
  }
  function drawGrid(ctx, axis, max, pad, width, height) { ctx.strokeStyle = "#dce3ed"; axis.fillStyle = "#68758a"; axis.font = "11px system-ui"; for (let index = 0; index < 6; index++) { const y = pad.t + height * index / 5; ctx.beginPath(); ctx.moveTo(pad.l, y); ctx.lineTo(pad.l + width, y); ctx.stroke(); axis.fillText("TTD " + Math.round(max * (1 - index / 5)), 2, y + 4); } $("#chartAxisCaption").textContent = "TTD per month"; }
  function area(ctx, values, fill, max, pad, width, height, lower) { ctx.beginPath(); values.forEach((value, index) => index ? ctx.lineTo(pointX(index, pad, width, values.length), pointY(value, max, pad, height)) : ctx.moveTo(pointX(index, pad, width, values.length), pointY(value, max, pad, height))); if (lower) [...lower].reverse().forEach((value, index) => ctx.lineTo(pointX(values.length - 1 - index, pad, width, values.length), pointY(value, max, pad, height))); else { ctx.lineTo(pointX(values.length - 1, pad, width, values.length), pad.t + height); ctx.lineTo(pad.l, pad.t + height); } ctx.closePath(); ctx.fillStyle = fill; ctx.fill(); }
  function drawAreas(ctx, series, max, pad, width, height) { if (api.state.showOperational) area(ctx, series.operationalRequirement, "rgba(38,113,217,.12)", max, pad, width, height); if (api.state.showDebt) area(ctx, series.overallRequirement, "rgba(216,132,22,.18)", max, pad, width, height, series.operationalRequirement); if (api.state.showActual) area(ctx, series.actualRevenue, "rgba(21,154,116,.12)", max, pad, width, height); if (api.state.showExpected) area(ctx, series.expectedComplete ? series.completeExpectedRevenue : series.configuredPricingRevenue, series.expectedComplete ? "rgba(118,87,201,.10)" : "rgba(198,122,18,.08)", max, pad, width, height); }
  function drawLines(ctx, series, max, pad, width, height) { const lines = []; if (api.state.showOperational) lines.push([series.operationalRequirement, colors.operational, []]); if (api.state.showDebt) lines.push([series.overallRequirement, colors.overall, []]); if (api.state.showActual) lines.push([series.actualRevenue, colors.actual, []]); if (api.state.showExpected) lines.push([series.expectedComplete ? series.completeExpectedRevenue : series.configuredPricingRevenue, series.expectedComplete ? colors.expected : colors.incomplete, [7, 5]]); window.hrplusChartHits = []; lines.forEach(([values, color, dash]) => { ctx.strokeStyle = color; ctx.lineWidth = 2.5; ctx.setLineDash(dash); ctx.beginPath(); values.forEach((value, index) => index ? ctx.lineTo(pointX(index, pad, width, values.length), pointY(value, max, pad, height)) : ctx.moveTo(pointX(index, pad, width, values.length), pointY(value, max, pad, height))); ctx.stroke(); ctx.setLineDash([]); values.forEach((value, index) => { const x = pointX(index, pad, width, values.length), y = pointY(value, max, pad, height); ctx.fillStyle = color; ctx.beginPath(); ctx.arc(x, y, 4, 0, Math.PI * 2); ctx.fill(); window.hrplusChartHits.push({ monthIndex: index, x, y, radius: 10 }); }); }); }
  function drawMonthLabels(ctx, series, max, pad, width, height) { if (!$("#showValueLabels").checked) return; ctx.fillStyle = "#68758a"; ctx.font = "11px system-ui"; series.months.forEach((month, index) => ctx.fillText(month.toLocaleDateString("en-TT", { month: "short" }), pointX(index, pad, width, series.months.length) - 14, pad.t + height + 22)); }
  function updateControls(series) { const expectedLabel = series.expectedComplete ? "Expected Revenue" : "Configured Pricing Revenue — Incomplete"; $("#expectedToggle").textContent = (api.state.showExpected ? "✓ " : "○ ") + expectedLabel; $("#actualToggle").textContent = (api.state.showActual ? "✓ " : "○ ") + "Actual Revenue"; $("#operationalToggle").textContent = (api.state.showOperational ? "✓ " : "○ ") + "Operational Requirement"; $("#debtToggle").textContent = (api.state.showDebt ? "✓ " : "○ ") + "Include Debt"; $("#legend").innerHTML = `<span>Operational Requirement</span><span>Overall Requirement</span><span>Actual Revenue</span><span>${expectedLabel}</span>`; $("#chartExplanation").textContent = "The blue area shows normalized monthly operational requirements. The amber band represents debt added above operational requirements. The dark Overall Requirement line shows the total monthly amount the business must fund. Revenue lines show actual and pricing-based monthly revenue." + (series.expectedComplete ? "" : " The amber dashed revenue line includes configured module rates only and is not the complete expected revenue."); }
  function updateViewport() { if (!api) return; const series = api.getSeries(), box = $("#chartScroll"), first = Math.min(series.months.length - 1, Math.floor(box.scrollLeft / Math.max(120, box.clientWidth / 6))), last = Math.min(series.months.length - 1, first + 5), months = series.months.slice(first, last + 1); $("#visiblePeriod").textContent = "Showing " + months[0].toLocaleDateString("en-TT", { month: "long", year: "numeric" }) + " – " + months[months.length - 1].toLocaleDateString("en-TT", { month: "long", year: "numeric" }); }
  function showTooltip(event) { const canvas = $("#trendChart"), rect = canvas.getBoundingClientRect(), scale = canvas.width / rect.width, px = (event.clientX - rect.left) * scale, py = (event.clientY - rect.top) * scale, hit = (window.hrplusChartHits || []).find((item) => Math.hypot(item.x - px, item.y - py) <= item.radius); if (!hit) return hideTooltip(); const series = api.getSeries(), index = hit.monthIndex, operational = series.operationalRequirement[index], debt = series.debtRequirement[index], overall = series.overallRequirement[index], actual = series.actualRevenue[index], expected = series.expectedComplete ? series.completeExpectedRevenue[index] : series.configuredPricingRevenue[index], tip = $("#chartTooltip"); tip.innerHTML = `<strong>${series.months[index].toLocaleDateString("en-TT", { month: "long", year: "numeric" })}</strong><div>Operational Requirement: ${money(operational)}</div><div>Debt Requirement: ${money(debt)}</div><div>Overall Requirement: ${money(overall)}</div><br><div>Actual Revenue: ${money(actual)}</div><div>${series.expectedComplete ? "Expected Revenue" : "Configured Pricing Revenue"}: ${money(expected)}</div><div>Operating ${actual >= operational ? "Profit" : "Loss"}: ${money(Math.abs(actual - operational))}</div><div>Funding ${actual >= overall ? "Surplus" : "Shortfall"}: ${money(Math.abs(actual - overall))}</div><div>Overall Coverage: ${overall ? (actual / overall * 100).toFixed(1) : "0.0"}%</div>`; tip.style.display = "block"; }
  function hideTooltip() { $("#chartTooltip").style.display = "none"; }
  window.HRplusFinancialChart = { initialize, render, destroy() { api = null; } };
})();
